### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'avatar_decoration'

### ISSUE THREAD

**Issue by jasper12112** [ahnaf-zamil/zenora#12]
While using this I got a unexpected error. I have used this package for more than 3 months and today this started happening.

Full trace:
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from keep_alive import keep_alive
  File "/home/runner/DCBotAPI/keep_alive.py", line 29, in <module>
    client = APIClient(token, client_secret=client_sc)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/zenora/client.py", line 58, in __init__
    self._validate_token()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/zenora/client.py", line 62, in _validate_token
    self.users.get_current_user()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/zenora/impl/userapi.py", line 48, in get_current_user
    return OwnUser(**payload)
TypeError: __init__() got an unexpected keyword argument 'avatar_decoration'

**Comment by ahnaf-zamil** [comment]
Are you using the version from Pypi or Github? The github version has the latest changes

**Comment by ahnaf-zamil** [comment]
Closing due to inactivity
