### ISSUE TITLE
The errors.py file doesn't work as expected.

### ISSUE THREAD

**Issue by ghost** [ahnaf-zamil/zenora#14]
**Expected Output**
AuthenticationError: {message}

**Actual Output**
KeyError: 'message'

**Screenshots**
Flask Debug mode.

![Flask Debug mode.](https://user-images.githubusercontent.com/72381315/187296051-92eb735b-a878-44d8-96e0-eab606876eef.png)

**Comment by ghost** [comment]
**Until this is fixed. (I really do not know what is causing the error) I will be using the way from the discord docs.**

**Comment by ahnaf-zamil** [comment]
Thanks for making this issue @ANDREI12333 

It appears that the Discord API has changed up their auth error fields and I haven't updated it to it. I will get started on this as soon as I can, so hold on tight!

**Comment by ahnaf-zamil** [comment]
Could you post the full error message? The traceback on console, if possible

**Comment by ghost** [comment]
**I tried using a wrong client secret and a wrong exception showed up. You can see it below. (This is the errors.py problem.)**

```
Traceback (most recent call last):
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\asgiref\sync.py", line 218, in __call__
    return call_result.result()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\asgiref\sync.py", line 284, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "C:\Users\abc\Documents\PythonProjects\ZenoraFlaskTest\main.py", line 12, in get
    access_token = client.oauth.get_access_token(
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\zenora\impl\oauthapi.py", line 54, in get_access_token
    payload = Request.make_request(
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\zenora\request.py", line 83, in make_request
    return req.execute()
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\zenora\request.py", line 74, in execute
    return raise_error_or_return(r)  # type: ignore[return-value]
  File "C:\Users\abc\AppData\Local\Programs\Python\Python310\Lib\site-packages\zenora\errors.py", line 45, in raise_error_or_return
    raise AuthenticationError(json_data["message"])
KeyError: 'message'
```

**Comment by ahnaf-zamil** [comment]
Hmm, seems like I've predicted it right. Let me assign myself
