### ISSUE TITLE
cant install zenora on centos

### ISSUE THREAD

**Issue by CreedoW** [ahnaf-zamil/zenora#22]
```
[root@vps75267491 profile.mwah.ro]# pip3 install --user Zenora
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting Zenora
  Could not find a version that satisfies the requirement Zenora (from versions: )
No matching distribution found for Zenora

```

```
[root@vps75267491 profile.mwah.ro]# pip3 install git+https://gitlab.com/ahnaf-zamil/zenora --user
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting git+https://gitlab.com/ahnaf-zamil/zenora
  Cloning https://gitlab.com/ahnaf-zamil/zenora to /tmp/pip-zaed0g0q-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-zaed0g0q-build/setup.py", line 23, in <module>
        import zenora
      File "/tmp/pip-zaed0g0q-build/zenora/__init__.py", line 27, in <module>
        from .models.snowflake import *
      File "/tmp/pip-zaed0g0q-build/zenora/models/snowflake.py", line 22, in <module>
        from typing import Final, List, TypeVar, Any, Union
    ImportError: cannot import name 'Final'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-zaed0g0q-build/

```

**Comment by ahnaf-zamil** [comment]
Check your Python version. Minimum should be 3.8
