### ISSUE TITLE
ValueError: Non keyword-only attributes are not allowed after a keyword-only attribute.

### ISSUE THREAD

**Issue by eltrevii** [ahnaf-zamil/zenora#3]
i tried t run zenora flask auth with discord example and it gives erro
i used `python app.py`
output:
```Traceback (most recent call last):
  File "D:\USUARIO\Downloads\zenora-master\zenora-master\examples\oauth_with_flask\app.py", line 22, in <module>
    from zenora import APIClient
  File "D:\USUARIO\Downloads\zenora-master\zenora-master\examples\oauth_with_flask\zenora\__init__.py", line 25, in <module>
    from .models.connection import *
  File "D:\USUARIO\Downloads\zenora-master\zenora-master\examples\oauth_with_flask\zenora\models\connection.py", line 23, in <module>
    from zenora.deserializers import deserialize_server_integration
  File "D:\USUARIO\Downloads\zenora-master\zenora-master\examples\oauth_with_flask\zenora\deserializers.py", line 25, in <module>
    from .models.integration import Integration
  File "D:\USUARIO\Downloads\zenora-master\zenora-master\examples\oauth_with_flask\zenora\models\integration.py", line 38, in <module>
    class Integration:
  File "C:\Program Files\Python39\lib\site-packages\attr\_make.py", line 847, in wrap
    builder = _ClassBuilder(
  File "C:\Program Files\Python39\lib\site-packages\attr\_make.py", line 470, in __init__
    attrs, base_attrs, base_map = _transform_attrs(
  File "C:\Program Files\Python39\lib\site-packages\attr\_make.py", line 413, in _transform_attrs
    raise ValueError(
ValueError: Non keyword-only attributes are not allowed after a keyword-only attribute.  Attribute in question: Attribute(name='type', default=NOTHING, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=<class 'str'>, converter=None, kw_only=False)```

**Comment by ahnaf-zamil** [comment]
Hm, that is an issue with the Integration class. I will fix it in the latest release. Thanks for letting me know :)

**Comment by eltrevii** [comment]
okay thanks... when will you do the next release

**Comment by ahnaf-zamil** [comment]
Already done. Zenora v0.0.3 has been released yesterday

**Comment by eltrevii** [comment]
awesome
