### ISSUE TITLE
for x in json_data["errors"]: KeyError: 'errors'

### ISSUE THREAD

**Issue by IndoRexian** [ahnaf-zamil/zenora#7]
I am using Zenora with flask and hosting it with gunicorn. Everything is fine when i locally test it, but when hosting I am always getting this error:
```
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
worker.init_process()
File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
self.load_wsgi()
File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
self.wsgi = self.app.wsgi()
File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
return self.load_wsgiapp()
File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
return util.import_app(self.app_uri)
File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
mod = importlib.import_module(module)
File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/workspace/mcoc.py", line 19, in <module>
client = APIClient(token=token, client_secret=client_secret)
File "/app/.heroku/python/lib/python3.9/site-packages/zenora/client.py", line 57, in __init__
self._validate_token()
File "/app/.heroku/python/lib/python3.9/site-packages/zenora/client.py", line 61, in _validate_token
self.users.get_current_user()
File "/app/.heroku/python/lib/python3.9/site-packages/zenora/impl/userapi.py", line 55, in get_current_user
payload = Request.make_request(self._token, url, "GET")
File "/app/.heroku/python/lib/python3.9/site-packages/zenora/request.py", line 83, in make_request
return req.execute()
File "/app/.heroku/python/lib/python3.9/site-packages/zenora/request.py", line 74, in execute
return raise_error_or_return(r)  # type: ignore[return-value]
File "/app/.heroku/python/lib/python3.9/site-packages/zenora/errors.py", line 49, in raise_error_or_return
for x in json_data["errors"]:
KeyError: 'errors'
```
I am pretty sure this is some error/bug coming from `errors.py` but can't seem to find out. I have double checked my credentials and there seems to be nothing wrong that.

**Comment by ahnaf-zamil** [comment]
Thanks for making this issue, I will take a look at it

**Comment by IndoRexian** [comment]
> Thanks for making this issue, I will take a look at it

Thnx for replying! But seems like this issue is fixed!
Thank you
