### ISSUE TITLE
Import Error: cannot import name 'Final' from 'typing'

### ISSUE THREAD

**Issue by Cupara** [ahnaf-zamil/zenora#8]
Here is the output:
`  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Users\schiz\.virtualenvs\SerenityDashboard-UkXZyhH1\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\schiz\.virtualenvs\SerenityDashboard-UkXZyhH1\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\schiz\.virtualenvs\SerenityDashboard-UkXZyhH1\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\schiz\AppData\Local\Temp\pip-build-env-a2ot4sx0\overlay\Lib\site-packages\setuptools\build_meta.py", line 178, in get_requires_for_build_wheel
          config_settings, requirements=['wheel'])
        File "C:\Users\schiz\AppData\Local\Temp\pip-build-env-a2ot4sx0\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "C:\Users\schiz\AppData\Local\Temp\pip-build-env-a2ot4sx0\overlay\Lib\site-packages\setuptools\build_meta.py", line 282, in run_setup
          self).run_setup(setup_script=setup_script)
        File "C:\Users\schiz\AppData\Local\Temp\pip-build-env-a2ot4sx0\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 23, in <module>
          import zenora
        File "C:\Users\schiz\AppData\Local\Temp\pip-req-build-wgmyaptb\zenora\__init__.py", line 27, in <module>
          from .models.snowflake import *
        File "C:\Users\schiz\AppData\Local\Temp\pip-req-build-wgmyaptb\zenora\models\snowflake.py", line 22, in <module>
          from typing import Final, List, TypeVar, Any, Union
      ImportError: cannot import name 'Final' from 'typing' (c:\panda3d-1.10.11-x64\python\lib\typing.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
`

I don't know why panda3d is there but I have attempted to avoid using panda3d since I'm working with building a login not a game.

**Comment by Cupara** [comment]
I got it figured out, I used pip to install, just wasn't capitalizing the 'Z' when trying.

**Comment by ahnaf-zamil** [comment]
One more thing
`ImportError: cannot import name 'Final' from 'typing' (c:\panda3d-1.10.11-x64\python\lib\typing.py)`

It's using the `typing` from the Panda3D engine's Python library, not the standard Python installation. Make sure you are using the standard Python installation which is 3.8+
